[workspace]
channels = ["conda-forge", "bioconda"]
name = "stephen.cristiano"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]
ginfo = {cmd="R -e 'BiocManager::install(\"GenomeInfoDb\")'"}
hg38 = {cmd="R -e 'BiocManager::install(\"BSgenome.Hsapiens.UCSC.hg38\")'", depends-on="ginfo"}
hg19 = {cmd="R -e 'BiocManager::install(\"BSgenome.Hsapiens.UCSC.hg19\")'", depends-on="ginfo"}
txdb = {cmd="R -e 'BiocManager::install(c(\"TxDb.Hsapiens.UCSC.hg19.knownGene\", \"TxDb.Hsapiens.UCSC.hg38.knownGene\"))'", depends-on="hg38"}

[dependencies]
cmake = ">=4.0.3,<5"
r-base = ">=4.4.3,<4.5"
r-mass = ">=7.3_64,<8"
r-ggplot2 = ">=3.5.2,<4"
"r-r.utils" = ">=2.13.0,<3"
bioconductor-genomicranges = ">=1.58.0,<2"
r-biocmanager = ">=1.30.26,<2"
bioconductor-genomeinfodb = ">=1.42.0,<2"
bioconductor-genomeinfodbdata = ">=1.2.13,<2"
r-tidyverse = ">=2.0.0,<3"
"r-aws.s3" = ">=0.3.22,<0.4"
r-envstats = ">=3.1.0,<4"
r-ggalluvial = ">=0.12.5,<0.13"
git-lfs = ">=3.7.1,<4"
"r-data.table" = ">=1.17.8,<2"
r-proc = ">=1.19.0.1,<2"
r-tidymodels = ">=1.4.1,<2"
r-recipes = ">=1.3.1,<2"
r-readxl = ">=1.4.5,<2"
r-ggpubr = ">=0.6.2,<0.7"
r-here = ">=1.0.1,<2"
r-devtools = ">=2.4.5,<3"
r-scales = ">=1.4.0,<2"
r-cowplot = ">=1.2.0,<2"
